version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: pcp-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Jr011207
      POSTGRES_DB: pcp_db
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data